# Use this file to pull GenieACS from DockerHub #

version: "3"
services:
# Dockerfile here: https://github.com/docker-library/mongo/blob/6932ac255d29759af9a74c6931faeb02de0fe53e/4.0/Dockerfile
    mongo:
        image: mongo:4.0 
        restart: always
        container_name: "mongo"
        environment:
#            - MONGO_INITDB_ROOT_USERNAME=userchange
#            - MONGO_INITDB_ROOT_PASSWORD=passwordchange
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/var/log/mongodb
        volumes:
            - data_db:/data/db
            - data_configdb:/data/configdb
        expose: 
            - 27017
        networks:
            - genieacs_network

### WARNING: NOT RECOMMENDED TO RUN THIS SERVICE (mongo-express) IN PRODUCTION ENVIRONMENTS ###
# Dockerfile here: https://github.com/mongo-express/mongo-express-docker/blob/b089fe7708d9dd619d648a6ec226fe0175b27740/Dockerfile
#    mongo-express: 
#        image: mongo-express
#        container_name: "mongo-express"
#        restart: always
#        depends_on:
#            - 'mongo'
#        ports:
#            - 8081:8081
#        environment:
##            - ME_CONFIG_MONGODB_ADMINUSERNAME=user
##            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#            - ME_CONFIG_MONGODB_SERVER=mongo
#            - ME_CONFIG_BASICAUTH_USERNAME=admin
#            - ME_CONFIG_BASICAUTH_PASSWORD=mongo2018
#        networks:
#            - genieacs_network

# Dockerfile here: https://github.com/neir-bohara/Genieacs/blob/main/Dockerfile
    genieacs:
        depends_on:
            - 'mongo'
        image: neir/genieacs:1.2.0
        restart: always
        container_name: "genieacs"
        environment:
            - GENIEACS_UI_JWT_SECRET=changeme
            - GENIEACS_CWMP_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-cwmp-access.log
            - GENIEACS_NBI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-nbi-access.log
            - GENIEACS_FS_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-fs-access.log
            - GENIEACS_UI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-ui-access.log
            - GENIEACS_DEBUG_FILE=/var/log/genieacs/genieacs-debug.yaml
            - GENIEACS_EXT_DIR=/opt/genieacs/ext
            - GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo/genieacs
        ports:
            - "7547:7547"
            - "7557:7557"
            - "7567:7567"
            - "3000:3000"
        volumes:
            - opt_volume:/opt
        networks:
            - genieacs_network

### THIS SERVICE IS JUST FOR TESTING PURPOSES ###
# Dockerfile here: https://hub.docker.com/r/drumsergio/genieacs-sim/dockerfile
#    genieacs-sim:
#        depends_on:
#            - 'genieacs'
#        image: drumsergio/genieacs-sim
#        container_name: "genieacs-sim"
#        networks:
#            - genieacs_network

volumes:
    data_db:
    data_configdb:
    opt_volume:

networks:
    genieacs_network:
